# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{findable_by}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thiago Moretto"]
  s.date = %q{2010-11-17}
  s.description = %q{Even easier to find records!}
  s.email = %q{thiago@moretto.eng.br}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "init.rb",
     "lib/findable_by.rb",
     "lib/findable_by/finders/between_finder.rb",
     "lib/findable_by/finders/equals_finder.rb",
     "lib/findable_by/finders/like_finder.rb",
     "lib/findable_by/finders/proc_finder.rb",
     "lib/findable_by/finders/scope_finder.rb",
     "lib/findable_by/version.rb"
  ]
  s.homepage = %q{http://github.com/thiagomoretto/findable_by}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Improving a way how you find records!}
  s.test_files = [
    "test/connection/native_sqlite3/in_memory_connection.rb",
     "test/findable_by_test.rb",
     "test/schema/schema.rb",
     "test/support/models.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

